# Calculus and Algebra problems

## Calculus

Exercise 1: Build a linear function  f(x)=− 0.5x+4  on  x∈[−3,3] ; create a graph and table.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

def f(x): return -0.5*x + 4 #function
x = np.linspace(-3, 3, 100) #domain

In [ ]:
plt.plot(x, f(x)) #plot of function on domain

In [ ]:
f1 = pd.DataFrame({'x': x, 'f(x)': f(x)})
f1.head()

Exercise 2: Build an exponential function  f(x)=3∗(100)^x  on  x∈[−3,3] ; create a graph and table.

In [ ]:
def f(x): return 3*(100**x)
x = np.linspace(-3, 3, 100)
plt.plot(x, f(x))

In [ ]:
f2 = pd.DataFrame({'x': x, 'f(x)': f(x)})
f2.head()

Exercise 3: Build a quadratic function  f(x)=3(x−1)^2−4  on  x∈[−5,5] ; create a graph and table.

In [ ]:
def f(x): return 3*(x - 1)**2 - 4
x = np.linspace(-5, 5, 100)
plt.plot(x, f(x))

In [ ]:
f3 = pd.DataFrame({'x': x, 'f(x)': f(x)})
f3.head()

## Linear Algebra

### Exercise 1 : Sum of two matrices

Suppose we have two matrices A and B.
```py
A = [[1,2],[3,4]]
B = [[4,5],[6,7]]

then we get
A+B = [[5,7],[9,11]]
A-B = [[-3,-3],[-3,-3]]
```

Make the sum of two matrices using Python with Numpy

In [1]:
# importing numpy as np
import numpy as np
  
  
# creating first matrix
A = np.array([[1, 2], [3, 4]])
  
# creating second matrix
B = np.array([[4, 5], [6, 7]])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
  
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


### Exercise 2: Sum of two lists

There will be many situations in which we'll have to find index wise summation of two different lists. This can have possible applications in day-to-day programming. In this exercise we will solve the same problem with various ways in which this task can be performed.

We have the following two lists:
```py
list1 = [2, 5, 4, 7, 3]
list2 = [1, 4, 6, 9, 10]
```

Now let's use Python code to demonstrate addition of two lists.


In [2]:
# Naive method

# initializing lists
list1 = [2, 5, 4, 7, 3]
list2 = [1, 4, 6, 9, 10]
  
# printing original lists
print ("Original list 1 : " + str(list1))
print ("Original list 2 : " + str(list2))
  
# using naive method to 
# add two list 
res_list = []
for i in range(0, len(list1)):
    res_list.append(list1[i] + list2[i])
  
# printing resultant list 
print ("Resultant list is : " + str(res_list))

Original list 1 : [2, 5, 4, 7, 3]
Original list 2 : [1, 4, 6, 9, 10]
Resultant list is : [3, 9, 10, 16, 13]


In [3]:
# Use list comprehensions to perform addition of the two lists:

# initializing lists

  
# printing original lists

  
# using list comprehension to add two list 

  
# printing resultant list 


In [ ]:
# Use map() + add():

# initializing lists

  
# printing original lists

  
# using map() + add() to add two list 

  
# printing resultant list 

In [4]:
# Use zip() + sum():

# initializing lists

  
# printing original lists

  
# Using zip() + sum() to add two list 

  
# printing resultant list 

### Exercise 3 : Dot multiplication

We have two matrices:
```py
matrix1 = [[1,7,3],
          [ 4,5,2],
          [ 3,6,1]]
matrix2 = [[5,4,1],
          [ 1,2,3],
          [ 4,5,2]]
```

A simple technique but expensive method for larger input datasets is using for loops. In this exercise we will first use nested for loops to iterate through each row and column of the matrices, and then we will perform the same multiplication using Numpy.

In [6]:
#Using a for loop input two matrices of size n x m
matrix1 = [[1,7,3],
          [ 4,5,2],
          [ 3,6,1]]
matrix2 = [[5,4,1],
          [ 1,2,3],
          [ 4,5,2]]
 
res = [[0 for x in range(3)] for y in range(3)]
 
# explicit for loops
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
 
            # resulted matrix
            res[i][j] += matrix1[i][k] * matrix2[k][j]
 
print (res)

[[24, 33, 28], [33, 36, 23], [25, 29, 23]]


In [7]:
# We need install numpy in order to import it
import numpy as np
 
# input two matrices
mat1 = ([1,7,3],[ 4,5,2],[ 3,6,1])
mat2 = ([5,4,1],[ 1,2,3],[ 4,5,2])
 
# This will return dot product
res = np.dot(mat1,mat2)
  
# print resulted matrix
print(res)

[[24 33 28]
 [33 36 23]
 [25 29 23]]
