# Algorithm Optimization problems

## Exercise 3: Implementing a KNN Algorithm with Scikit-learn

We will see how Python's Scikit-Learn library can be used to implement the KNN algorithm in less than 20 lines of code. Then the task will be to try to optimize the parameter of this algorithm.

**The dataset**

We are going to use the famous iris data set for our KNN example. The dataset consists of four attributes: sepal-width, sepal-length, petal-width and petal-length. These are the attributes of specific types of iris plant. The goal is to predict the class to which these plants belong. There are three classes in the dataset: Iris-setosa, Iris-versicolor and Iris-virginica.


**Library installation**


First let's install the Scikit-learn library by entering the following command in the terminal:

```py
pip install -U scikit-learn
```

Now let's see how to implement the KNN algorithm:

**Importing libraries**

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing and loading the dataset**

In [7]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

**Looking at the first rows of the data**

In [8]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

**Pre-processing**

Split dataset into attributes and labels

In [9]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

**Train Test split**

To avoid over-fitting, we will divide our dataset into training and test splits. This way our algorithm is tested on un-seen data to evaluate the performance of our algorithm. We will divide it into 80% training data and 20% for testing.

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

**Feature Scaling**

The majority of classifiers calculate the distance between two points by the Euclidean distance. If one of the features has a broad range of values, the distance will be governed by this particular feature. Therefore, the range of all features should be normalized so that each feature contributes approximately proportionately to the final distance.

It is a good practice to scale the features so that all of them can be uniformly evaluated.

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

**Train the KNN algorithm**

We will initialize it with one parameter: n_neigbours. This is basically the value for 'K'. After making the predictions we will try to otpimize this K value.

In [13]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

**Make predictions on our test data**

In [14]:
y_pred = classifier.predict(X_test)

**Evaluate the algorithm**

Confusion matrix, precision, recall and f1 score are the most commonly used metrics for classification problems.
The confusion_matrix and classification_report methods of the sklearn.metrics can be used to calculate these metrics.

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 9  0  0]
 [ 0  7  0]
 [ 0  0 14]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00         7
 Iris-virginica       1.00      1.00      1.00        14

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



**Optimizing our KNN algorithm**

There is no way to know beforehand which value of K yields the best results since the beginning. We randomly chose 5 as the K value.

To help find the best value of K:

1. First create a function that calculates the mean of error for all the predicted values where K ranges from 1 and 40. 
2. Plot the error values against K values.
3. Vary the test and training size along with the K value to see how your results differ and how can you improve the accuracy of your algorithm. 

In [ ]:
# Create an empty error list.
error = []

# Execute a loop from 1 to 40. In each iteration calculate the mean error for predicted values of test set
for i in range(1, 40):
    #initialize the KNN algorithm
    knn = KNeighborsClassifier(n_neighbors=i)
    #fit the train data
    knn.fit(X_train, y_train)
    #make predictions
    pred_i = knn.predict(X_test) 
    #append the result to the error list.
    error.append(np.mean(pred_i != y_test)) 

In [ ]:
# plot the error values against K values

plt.figure(figsize=(12, 6))
plt.plot(range(1, 40), error, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Error Rate K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier25 = KNeighborsClassifier(n_neighbors=25)
classifier25.fit(X_train, y_train)

In [ ]:
y_pred25 = classifier25.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred25))
print(classification_report(y_test, y_pred25))

Source:

https://www.geeksforgeeks.org/

https://stackabuse.com/big-o-notation-and-algorithm-analysis-with-python-examples/

https://stackabuse.com/quicksort-in-python/

https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/